#!/bin/bash

if [[ -e /media/matt/"Seagate Expansion Drive" ]] 
then
    if [[ ! -e /tmp/seagate_backups.log ]]
    then
        touch /tmp/seagate_backups.log
    fi
    rsync -avz --delete /home/matt/ /media/matt/"Seagate Expansion Drive"/Ubuntu-MattsPC-Backup > /tmp/seagate_backups.log
    date > /tmp/seagate_backups.log
fi
