#!/bin/bash

read TOPREPEND

for f in $@
do
    if [[ -f $f ]]
    then
        echo $TOPREPEND > /tmp/prepend.tmp
        cat $f >> /tmp/prepend.tmp
        cat /tmp/prepend.tmp > $f
    else 
        echo "$f does not exist"
    fi
done

